/* Paz's Sale — additive sharing layer. Does not modify auth, sync, storage, sales or catalog data. */
(function(){
  'use strict';
  const selected=new Set();
  let activeShareId=null;
  function getItems(){try{return typeof items!=='undefined'&&Array.isArray(items)?items:[]}catch{return[]}}
  function getItem(id){return getItems().find(i=>String(i.id)===String(id))}
  function fmt(n){try{return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0))}catch{return `$${Number(n||0).toFixed(2)}`}}
  function publicItemUrl(id){const u=new URL('/liquidacion-paz/item/',location.origin);u.searchParams.set('id',id);return u.toString()}
  function locationText(){try{return(typeof getSettings==='function'?getSettings()?.locationText:'')||'Quito, Ecuador'}catch{return'Quito, Ecuador'}}
  function itemText(item,withUrl=true){if(!item)return'';const bits=[`${item.title||'Artículo'} — ${fmt(item.askingPrice)}`];if(item.description)bits.push(item.description);if(locationText())bits.push(locationText());if(withUrl)bits.push(publicItemUrl(item.id));return bits.join('\n')}
  function marketplaceText(item){if(!item)return'';return[item.title||'Artículo',`Precio: ${fmt(item.askingPrice)}`,item.description||'',item.category?`Categoría: ${item.category}`:'',locationText()?`Ubicación: ${locationText()}`:'',`Detalles: ${publicItemUrl(item.id)}`].filter(Boolean).join('\n')}
  function toastSafe(msg){try{if(typeof toast==='function')return toast(msg)}catch(_){}console.log(msg)}
  async function copyText(text){if(navigator.clipboard?.writeText){try{await navigator.clipboard.writeText(text);return true}catch(_){}}const ta=document.createElement('textarea');ta.value=text;ta.setAttribute('readonly','');ta.style.position='fixed';ta.style.opacity='0';ta.style.pointerEvents='none';document.body.appendChild(ta);ta.select();ta.setSelectionRange(0,ta.value.length);let ok=false;try{ok=document.execCommand('copy')}catch(_){}ta.remove();return ok}
  async function nativeShare(item){if(!item)return;const payload={title:item.title||"Paz's Sale",text:`${item.title||'Artículo'} — ${fmt(item.askingPrice)}\n${item.description||''}`.trim(),url:publicItemUrl(item.id)};if(navigator.share){try{await navigator.share(payload);return}catch(e){if(e?.name==='AbortError')return}}await copyText(itemText(item,true));toastSafe('Texto y enlace copiados')}
  function whatsappShare(item){if(!item)return;window.open(`https://wa.me/?text=${encodeURIComponent(itemText(item,true))}`,'_blank','noopener')}
  async function copyLink(item){if(!item)return;await copyText(publicItemUrl(item.id));toastSafe('Enlace copiado')}
  async function marketplace(item){if(!item)return;const popup=window.open('https://www.facebook.com/marketplace/create/item','_blank');if(popup){try{popup.opener=null}catch(_){}}const ok=await copyText(marketplaceText(item));toastSafe(ok?(popup?'Texto para Marketplace copiado':'Texto copiado; abre Marketplace para publicarlo'):'Abriendo Marketplace')}
  function parseCardId(card){for(const b of[...card.querySelectorAll('button[onclick]')]){const s=b.getAttribute('onclick')||'';const m=s.match(/(?:editItem|openSale)\(['"]([^'"]+)['"]\)/);if(m)return m[1]}return null}
  function installStyles(){if(document.getElementById('pazShareStyles'))return;const s=document.createElement('style');s.id='pazShareStyles';s.textContent='.paz-share-select{display:inline-flex;align-items:center;gap:6px;padding:7px 9px;border:1px solid rgba(1,33,105,.16);border-radius:999px;font-size:12px;font-weight:800;color:#012169;background:#fff;cursor:pointer}.paz-share-select input{width:16px;height:16px;accent-color:#012169}.paz-share-bulk{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap;margin:12px 0;padding:10px 12px;border:1px solid rgba(1,33,105,.16);border-radius:16px;background:rgba(1,33,105,.035)}.paz-share-bulk[hidden]{display:none!important}.paz-share-bulk strong{color:#012169}.paz-share-bulk .actions{display:flex;gap:8px;flex-wrap:wrap}.paz-share-dialog{border:0;border-radius:22px;padding:0;max-width:460px;width:calc(100% - 28px);box-shadow:0 24px 80px rgba(0,0,0,.28)}.paz-share-dialog::backdrop{background:rgba(0,0,0,.45)}.paz-share-shell{padding:20px}.paz-share-head{display:flex;justify-content:space-between;gap:14px;align-items:start}.paz-share-head h2{margin:3px 0 4px;color:#012169}.paz-share-head p{margin:0;color:#333;font-size:14px}.paz-share-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:18px}.paz-share-grid .btn{width:100%}.paz-share-close{border:0;background:transparent;font-size:26px;line-height:1;cursor:pointer;color:#012169}@media(max-width:520px){.paz-share-grid{grid-template-columns:1fr}.paz-share-bulk .actions{width:100%}.paz-share-bulk .actions .btn{flex:1}}';document.head.appendChild(s)}
  function installDialog(){if(document.getElementById('pazShareDialog'))return;const d=document.createElement('dialog');d.id='pazShareDialog';d.className='paz-share-dialog';d.innerHTML='<div class="paz-share-shell"><div class="paz-share-head"><div><div class="eyebrow">Compartir artículo</div><h2 id="pazShareTitle">Artículo</h2><p id="pazSharePrice"></p></div><button type="button" class="paz-share-close" aria-label="Cerrar">×</button></div><div class="paz-share-grid"><button type="button" class="btn dark" data-share-action="native">Compartir…</button><button type="button" class="btn ghost" data-share-action="wa">WhatsApp</button><button type="button" class="btn ghost" data-share-action="copy">Copiar enlace</button><button type="button" class="btn ghost" data-share-action="marketplace">Preparar Marketplace</button></div></div>';document.body.appendChild(d);d.querySelector('.paz-share-close').addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d)d.close()});d.querySelector('[data-share-action="native"]').addEventListener('click',()=>nativeShare(getItem(activeShareId)));d.querySelector('[data-share-action="wa"]').addEventListener('click',()=>whatsappShare(getItem(activeShareId)));d.querySelector('[data-share-action="copy"]').addEventListener('click',()=>copyLink(getItem(activeShareId)));d.querySelector('[data-share-action="marketplace"]').addEventListener('click',()=>marketplace(getItem(activeShareId)))}
  function openMenu(id){const item=getItem(id);if(!item)return;activeShareId=id;document.getElementById('pazShareTitle').textContent=item.title||'Artículo';document.getElementById('pazSharePrice').textContent=`${fmt(item.askingPrice)} · ${locationText()}`;document.getElementById('pazShareDialog').showModal()}
  function installBulkBar(){const inv=document.getElementById('inventory');if(!inv||document.getElementById('pazShareBulk'))return;const filters=inv.querySelector('.filters');if(!filters)return;const bar=document.createElement('div');bar.id='pazShareBulk';bar.className='paz-share-bulk';bar.hidden=true;bar.innerHTML='<strong id="pazShareCount">0 seleccionados</strong><div class="actions"><button type="button" class="btn dark" id="pazShareSelected">Compartir seleccionados</button><button type="button" class="btn ghost" id="pazWaSelected">WhatsApp</button><button type="button" class="btn ghost" id="pazPdfSelected">Mini catálogo PDF</button><button type="button" class="btn ghost" id="pazClearSelected">Limpiar</button></div>';filters.insertAdjacentElement('afterend',bar);document.getElementById('pazShareSelected').addEventListener('click',shareSelected);document.getElementById('pazWaSelected').addEventListener('click',waSelected);document.getElementById('pazPdfSelected').addEventListener('click',pdfSelected);document.getElementById('pazClearSelected').addEventListener('click',clearSelected)}
  function selectedItems(){const map=new Map(getItems().map(i=>[String(i.id),i]));return[...selected].map(id=>map.get(String(id))).filter(i=>i&&i.status!=='VENDIDO')}
  function selectedText(){const list=selectedItems();const lines=[`Paz's Sale — ${list.length} artículo${list.length===1?'':'s'}`,''];list.forEach((i,n)=>{lines.push(`${n+1}. ${i.title} — ${fmt(i.askingPrice)}`);lines.push(publicItemUrl(i.id));if(n<list.length-1)lines.push('')});return lines.join('\n')}
  function updateBulk(){const bar=document.getElementById('pazShareBulk');if(!bar)return;const list=selectedItems();bar.hidden=!list.length;document.getElementById('pazShareCount').textContent=`${list.length} seleccionado${list.length===1?'':'s'}`;document.querySelectorAll('[data-paz-select]').forEach(cb=>{cb.checked=selected.has(cb.dataset.pazSelect)})}
  function clearSelected(){selected.clear();updateBulk()}
  async function shareSelected(){const list=selectedItems();if(!list.length)return;const text=selectedText();if(navigator.share){try{await navigator.share({title:"Paz's Sale",text});return}catch(e){if(e?.name==='AbortError')return}}await copyText(text);toastSafe('Lista de artículos copiada')}
  function waSelected(){if(!selectedItems().length)return;window.open(`https://wa.me/?text=${encodeURIComponent(selectedText())}`,'_blank','noopener')}
  function pdfSelected(){const list=selectedItems();if(!list.length)return;try{if(typeof catalogSelection==='undefined'||typeof renderCatalog!=='function')throw new Error('catalog unavailable');catalogSelection.clear();list.forEach(i=>catalogSelection.add(i.id));renderCatalog();if(typeof showTab==='function')showTab('catalog');setTimeout(()=>document.getElementById('generatePdf')?.click(),50)}catch(e){console.warn(e);toastSafe('No pude preparar el PDF en este momento')}}
  function decorateCard(card,isInventory){if(card.dataset.pazShareDecorated==='1')return;const id=parseCardId(card);if(!id)return;const item=getItem(id);if(!item||item.status==='VENDIDO')return;const actions=card.querySelector('.card-actions');if(!actions)return;card.dataset.pazShareDecorated='1';if(isInventory){const label=document.createElement('label');label.className='paz-share-select';label.title='Seleccionar para compartir varios';const cb=document.createElement('input');cb.type='checkbox';cb.dataset.pazSelect=String(id);cb.checked=selected.has(String(id));cb.addEventListener('change',()=>{cb.checked?selected.add(String(id)):selected.delete(String(id));updateBulk()});label.append(cb,document.createTextNode('Seleccionar'));actions.appendChild(label)}const btn=document.createElement('button');btn.type='button';btn.className='btn ghost';btn.textContent='Compartir';btn.dataset.pazShare=String(id);btn.addEventListener('click',()=>openMenu(id));actions.appendChild(btn)}
  function decorate(){document.querySelectorAll('#inventoryGrid .card').forEach(c=>decorateCard(c,true));document.querySelectorAll('#recentItems .card').forEach(c=>decorateCard(c,false));updateBulk()}
  function observe(){['inventoryGrid','recentItems'].forEach(id=>{const el=document.getElementById(id);if(el)new MutationObserver(()=>queueMicrotask(decorate)).observe(el,{childList:true,subtree:true})})}
  function init(){installStyles();installDialog();installBulkBar();observe();decorate()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
  window.PazSaleShare={open:openMenu,shareSelected,whatsappSelected:waSelected,pdfSelected,clearSelected,publicItemUrl};
})();
